
  notify:
    if: always()
    name: Notify Slack
    uses: slackapi/slack-github-action@v2
    with:
      payload: |
        {
          "text": "Deployment Notification: Job '{{ job.status }}' on environment '{{ env.ENV }}'\nRepository: {{ github.repository }}\nBranch: {{ github.ref }}\nSHA: {{ github.sha }}\nRun URL: ${{ github.run_url }}"
        }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  