name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to DEV"

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - run: echo "Deploying to QA"

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploying to PROD"
